webapp/favorite_searches/models.py
from datetime import datetime
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

from webapp.model import db


class FavoriteSearches(db.Model):
    __tablename__ = 'favorite_searches'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )
    query_name = db.Column(db.String(50), nullable=False)
    user_query = db.Column(db.String(100), nullable=False)
    chosen_categoryid = db.Column(db.Integer, nullable=False)
    filter_request = db.Column(db.Text, nullable=False)
    date_of_creation = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.now(),
        )
    statistic_status = db.Column(db.Boolean, nullable=True)
    statistic_start_date = db.Column(db.DateTime, nullable=True)
    user = relationship('User', backref='favorite_searches')

    def __repr__(self):
        return '<user_id={} query={} filter_request={}>'.format(
            self.user_id, self.user_query, self.filter_request)


class StatisticItems(db.Model):
    __tablename__ = 'statistic_items'
    id = db.Column(db.Integer, primary_key=True)
    query_id = db.Column(
        db.Integer,
        db.ForeignKey('favorite_searches.id', ondelete='CASCADE'),
        index=True,
        nullable=False,
    )
    item_id = db.Column(db.String(50), nullable=False)
    item_name = db.Column(db.String(200), nullable=True)
    item_current_price = db.Column(db.String(10), nullable=False)
    end_time = db.Column(db.DateTime, nullable=False)
    final_price = db.Column(db.Integer, nullable=True)
    item_url = db.Column(db.String(200), nullable=False)
    bids = db.Column(db.Integer, nullable=True)
    favorite_searches = relationship(
        'FavoriteSearches',
        backref='statistic_items',
        )

    def __repr__(self):
        return '<query_id={} end_time={} final_price={}>'.format(
            self.query_id, self.end_time, self.final_price)

webapp/ebay_search/views.py
from flask import Blueprint, flash, render_template, request

from webapp.ebay_search.find_items import (
    find_items_advanced, add_to_watch_list, get_user_watch_list,
    remove_from_user_watch_list, get_user_filters_request,
)
from webapp.ebay_search.models import EbayCategories
from webapp.user.decorators import user_required


blueprint = Blueprint('search', __name__, url_prefix='/search')


@blueprint.route('/')
@user_required
def search():
    # получаем категории товаров Ebay из базы данных для отображения на поисковой странице
    categories = EbayCategories.query.filter_by(
        category_level=1)
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем номер выбранной страницы, по умолчанию номер страницы = 1
    page_number = request.args.get('pagenumber')
    if not page_number:
        page_number = 1
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем значение фильтра, удаляемое из поискового запроса
    if filters_request:
        user_filters_list = get_user_filters_request(filters_request)
    else:
        user_filters_list = None
    # При направлении любого поискового запроса получаем с Ebay список 
    # избранных лотов пользователя
    if q:
        watch_items = get_user_watch_list()


    # обрабатываем поисковый запрос пользователя, номер выбранной страницы,
    # фильтры и передаем его в html
    if q:
        (results, total_pages, subcategory, subcategory_id, histogram_container_data
            ) = find_items_advanced(
            q,
            chosen_categoryid,
            page_number=page_number,
            user_filters_list=user_filters_list)

    search_request = {
        'title': 'Результаты поиска' if q else None,
        'categories': categories,
        'pagenumber': page_number,
        'userfilterslist': user_filters_list,
        'watch_list': watch_items if q else None,
        'results': results if q else None,
        'totalpages': total_pages if q else None,
        'subcategory': subcategory if q else None,
        'subcategoryid': subcategory_id if q else None,
        'histogram_container_data': histogram_container_data if q else None,
    }

    return render_template(
        'ebay_search/search.html',
        **search_request)


@blueprint.route('/add_to_watch_list')
def add_to():
    item_id = request.args.get('itemid')
    if item_id:
        add_to_watch_list(item_id)

        return render_template('ebay_search/add_to_watch_list.html')


@blueprint.route('/watch_list')
@user_required
def open_watch_list():
    watch_items = get_user_watch_list()
    return render_template(
        'ebay_search/watch_list.html', watch_list=watch_items)


@blueprint.route('/remove_item')
def remove_from():
    item_id = request.args.get('itemid')
    if item_id:
        remove_from_user_watch_list(item_id)
        return render_template('ebay_search/remove_from_watch_list.html')


@blueprint.context_processor
def filter_processor():
    def delete_filter_from_request(filters_request, value):
        """
        Функция удаляет фильтр из списка избранных фильтров
        пользователя по запросу с html
        """
        user_filters_request = get_user_filters_request(filters_request)
        for filters in user_filters_request:
            if (len(filters['filter_values']) == 1 and
                    value in filters['filter_values']):
                user_filters_request.remove(filters)
            elif value in filters['filter_values']:
                filters['filter_values'].remove(value)
        new_filters_request = ''
        for filters in user_filters_request:
            new_filters_request += f"{filters['filter_name']}:"
            for value in filters['filter_values']:
                new_filters_request += f"{value};"
        return new_filters_request
    return dict(new_filters_request=delete_filter_from_request)

webapp/favorite_searches/views.py
import io
from datetime import datetime
from flask import Blueprint, request, render_template, Response
from flask_login import current_user
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

from webapp import db
from webapp.favorite_searches.diagram_mpl import plot_statistics, plot_histogram
from webapp.favorite_searches.models import FavoriteSearches, StatisticItems
from webapp.user.decorators import user_required


blueprint = Blueprint(
    'favorite_searches', __name__, url_prefix='/favorite_searches')


@blueprint.route('/')
@user_required
def open_favorite_searches():
    favorite_searches_list = FavoriteSearches.query.filter(
        FavoriteSearches.user_id == current_user.id).order_by(
            FavoriteSearches.date_of_creation.desc()).all()

    return render_template(
        'favorite_searches/favorite_searches.html',
        favorite_searches_list=favorite_searches_list
    )


@blueprint.route('/add_to_favorite_searches')
@user_required
def add_to_favorite_searches():
    """
    Функция добавляет поиск в базу данных "Избранные поиски"
    """
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем имя сохраненного поискового запроса
    query_name = request.args.get('query_name')

    user_query_exists = FavoriteSearches.query.filter(
        FavoriteSearches.user_query == q).count()
    if not user_query_exists:
        new_user_query = FavoriteSearches(
            user_id=current_user.id,
            query_name=query_name,
            user_query=q,
            chosen_categoryid=chosen_categoryid,
            filter_request=filters_request,
        )
        db.session.add(new_user_query)
        db.session.commit()

        return render_template(
            'favorite_searches/add_to_favorite_searches.html')


@blueprint.route('/remove_from_favorite_searches')
def remove_from_favorite_searches():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        db.session.delete(favorite_search)
        db.session.commit()
        title = "Поиск успешно удален из 'Избранных поисков'"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/add_statistic')
def add_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = True
        favorite_search.statistic_start_date = datetime.now()
        db.session.commit()
        title = "Сбор статистики цен включен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/stop_statistic')
def stop_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = False
        favorite_search.statistic_start_date = None
        db.session.commit()
        title = "Сбор статистики цен выключен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/visualize_statistics')
def visualize_statistics():
    query_id = request.args.get('id')
    items_list = StatisticItems.query.filter(
        StatisticItems.query_id == query_id, StatisticItems.final_price.isnot(None)).order_by(
            StatisticItems.end_time.asc()).all()
    return render_template(
        'favorite_searches/visualize_statistics.html',
        items_list=items_list,
        query_id=query_id)


@blueprint.route('/visualize_diagram')
def visualize_diagram():
    query_id = request.args.get('id')
    diagram = plot_statistics(query_id)
    output = io.BytesIO()
    diagram = FigureCanvas(diagram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')


@blueprint.route('/visualize_histogram')
def visualize_histogram():
    query_id = request.args.get('id')
    histogram = plot_histogram(query_id)
    output = io.BytesIO()
    histogram = FigureCanvas(histogram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')

webapp/templates/favorite_searches/add_to_favorite_searches.html
{% extends "base.html" %} {% block content %}Поиск успешно добавлен в "Избранные
поиски"{% endblock %}

webapp/templates/favorite_searches/favorite_searches.html
{% extends "base.html" %} {% block content %} {% if favorite_searches_list %}
<h3>"Избранные поиски"</h3>
{% for user_search in favorite_searches_list %}
<div class="card">
  <div class="card-body">
    <p class="card-text my-1">Название поиска: {{ user_search.query_name }}</p>
    <p class="card-text my-1">Поисковый запрос: {{ user_search.user_query }}</p>
    <a
      class="btn btn-success btn-block my-1"
      role="button"
      href="{{ url_for(
                    'search.search',
                    q=user_search.user_query,
                    categoryid=user_search.chosen_categoryid,
                    filters=user_search.filter_request,
                    ) }}"
      >Применить поиск
    </a>
    <p class="card-text">
      <small
        >Сохранено: {{ user_search.date_of_creation.strftime('%d.%m.%Y') }}
      </small>
    </p>
    <a
      href="{{ url_for('favorite_searches.remove_from_favorite_searches', id=user_search.id) }}"
      target="_blank"
      class="btn btn-danger"
      role="button"
      >Удалить из "Избранных поисков"</a
    >
    {% if not user_search.statistic_status %}
    <a
      href="{{ url_for('favorite_searches.add_statistic', id=user_search.id) }}"
      target="_blank"
      class="btn btn-warning"
      role="button"
      >Включить сбор статистики цен на 7 дней</a
    >
    {% else %}
    <a
      href="{{ url_for('favorite_searches.stop_statistic', id=user_search.id) }}"
      target="_blank"
      class="btn btn-danger"
      role="button"
      >Выключить сбор статистики цен</a
    >
    <a
      href="{{ url_for('favorite_searches.visualize_statistics', id=user_search.id) }}"
      target="_blank"
      class="btn btn-info"
      role="button"
      >Показать статистику цен</a
    >
    {% endif %}
  </div>
</div>
{% endfor %} {% else %}
<h3>У Вас нет "Избранных поисков"</h3>
{% endif %} {% endblock %}

webapp/templates/favorite_searches/favorite_searches_action.html
{% extends "base.html" %} {% block content %}
<h3>{{ title }}</h3>
{% endblock %}

webapp/templates/favorite_searches/visualize_statistics.html
{% extends "base.html" %}

{% block content %}
    {% if items_list %}
        <div class="mt-2">
            <h3>Завершенные аукционы:</h3>
        </div>
        <div class="row mt-1 mb-5">
            <div class="col-12">
                <img src="/favorite_searches/visualize_diagram?id={{ query_id }}" alt="my plot">
            </div>
        </div>
        <div class="row mt-1 mb-5">
            <div class="col-12">
                <img src="/favorite_searches/visualize_histogram?id={{ query_id }}" alt="my plot">
            </div>
        </div>
        {% for item in items_list %}
            <div class="card">
                <div class="card-body">
                    <a href="{{ item.item_url }}" target="_blank" role="button">{{ item.item_name }}</a>
                    <p class="card-text my-1">Время завершения аукциона: {{ item.end_time }}</p>
                    <p class="card-text my-1">Итоговая цена: {{ item.final_price }} USD</p>
                    <p class="card-text my-1">Количество ставок: {{ item.bids }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>По данному запросу пока нет завершенных аукционов для сбора статистики цен</h3>
    {% endif %}
{% endblock %}