webapp/ebay_search/models.py
from webapp.model import db


class EbayCategories(db.Model):
    __tablename__ = 'ebay_categories'
    id = db.Column(db.Integer, primary_key=True)
    category_name = db.Column('categoryname', db.String(50), nullable=False)
    category_level = db.Column('categorylevel', db.Integer, nullable=False)
    category_id = db.Column(
        'categoryid', db.Integer, unique=True, nullable=False)
    categoryparent_id = db.Column('categoryparentid', db.Integer)

    def __repr__(self):
        return '<category_name={} category_id={}>'.format(
            self.category_name, self.category_id)

webapp/ebay_search/views.py
from flask import Blueprint, flash, render_template, request

from webapp.ebay_search.find_items import (
    find_items_advanced, add_to_watch_list, get_user_watch_list,
    remove_from_user_watch_list, get_user_filters_request,
)
from webapp.ebay_search.models import EbayCategories
from webapp.user.decorators import user_required


blueprint = Blueprint('search', __name__, url_prefix='/search')


@blueprint.route('/')
@user_required
def search():
    # получаем категории товаров Ebay из базы данных для отображения на поисковой странице
    categories = EbayCategories.query.filter_by(
        category_level=1)
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем номер выбранной страницы, по умолчанию номер страницы = 1
    page_number = request.args.get('pagenumber')
    if not page_number:
        page_number = 1
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем значение фильтра, удаляемое из поискового запроса
    if filters_request:
        user_filters_list = get_user_filters_request(filters_request)
    else:
        user_filters_list = None
    # При направлении любого поискового запроса получаем с Ebay список 
    # избранных лотов пользователя
    if q:
        watch_items = get_user_watch_list()


    # обрабатываем поисковый запрос пользователя, номер выбранной страницы,
    # фильтры и передаем его в html
    if q:
        (results, total_pages, subcategory, subcategory_id, histogram_container_data
            ) = find_items_advanced(
            q,
            chosen_categoryid,
            page_number=page_number,
            user_filters_list=user_filters_list)

    search_request = {
        'title': 'Результаты поиска' if q else None,
        'categories': categories,
        'pagenumber': page_number,
        'userfilterslist': user_filters_list,
        'watch_list': watch_items if q else None,
        'results': results if q else None,
        'totalpages': total_pages if q else None,
        'subcategory': subcategory if q else None,
        'subcategoryid': subcategory_id if q else None,
        'histogram_container_data': histogram_container_data if q else None,
    }

    return render_template(
        'ebay_search/search.html',
        **search_request)


@blueprint.route('/add_to_watch_list')
def add_to():
    item_id = request.args.get('itemid')
    if item_id:
        add_to_watch_list(item_id)

        return render_template('ebay_search/add_to_watch_list.html')


@blueprint.route('/watch_list')
@user_required
def open_watch_list():
    watch_items = get_user_watch_list()
    return render_template(
        'ebay_search/watch_list.html', watch_list=watch_items)


@blueprint.route('/remove_item')
def remove_from():
    item_id = request.args.get('itemid')
    if item_id:
        remove_from_user_watch_list(item_id)
        return render_template('ebay_search/remove_from_watch_list.html')


@blueprint.context_processor
def filter_processor():
    def delete_filter_from_request(filters_request, value):
        """
        Функция удаляет фильтр из списка избранных фильтров
        пользователя по запросу с html
        """
        user_filters_request = get_user_filters_request(filters_request)
        for filters in user_filters_request:
            if (len(filters['filter_values']) == 1 and
                    value in filters['filter_values']):
                user_filters_request.remove(filters)
            elif value in filters['filter_values']:
                filters['filter_values'].remove(value)
        new_filters_request = ''
        for filters in user_filters_request:
            new_filters_request += f"{filters['filter_name']}:"
            for value in filters['filter_values']:
                new_filters_request += f"{value};"
        return new_filters_request
    return dict(new_filters_request=delete_filter_from_request)

webapp/favorite_searches/views.py
import io
from datetime import datetime
from flask import Blueprint, request, render_template, Response
from flask_login import current_user
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

from webapp import db
from webapp.favorite_searches.diagram_mpl import plot_statistics, plot_histogram
from webapp.favorite_searches.models import FavoriteSearches, StatisticItems
from webapp.user.decorators import user_required


blueprint = Blueprint(
    'favorite_searches', __name__, url_prefix='/favorite_searches')


@blueprint.route('/')
@user_required
def open_favorite_searches():
    favorite_searches_list = FavoriteSearches.query.filter(
        FavoriteSearches.user_id == current_user.id).order_by(
            FavoriteSearches.date_of_creation.desc()).all()

    return render_template(
        'favorite_searches/favorite_searches.html',
        favorite_searches_list=favorite_searches_list
    )


@blueprint.route('/add_to_favorite_searches')
@user_required
def add_to_favorite_searches():
    """
    Функция добавляет поиск в базу данных "Избранные поиски"
    """
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем имя сохраненного поискового запроса
    query_name = request.args.get('query_name')

    user_query_exists = FavoriteSearches.query.filter(
        FavoriteSearches.user_query == q).count()
    if not user_query_exists:
        new_user_query = FavoriteSearches(
            user_id=current_user.id,
            query_name=query_name,
            user_query=q,
            chosen_categoryid=chosen_categoryid,
            filter_request=filters_request,
        )
        db.session.add(new_user_query)
        db.session.commit()

        return render_template(
            'favorite_searches/add_to_favorite_searches.html')


@blueprint.route('/remove_from_favorite_searches')
def remove_from_favorite_searches():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        db.session.delete(favorite_search)
        db.session.commit()
        title = "Поиск успешно удален из 'Избранных поисков'"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/add_statistic')
def add_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = True
        favorite_search.statistic_start_date = datetime.now()
        db.session.commit()
        title = "Сбор статистики цен включен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/stop_statistic')
def stop_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = False
        favorite_search.statistic_start_date = None
        db.session.commit()
        title = "Сбор статистики цен выключен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/visualize_statistics')
def visualize_statistics():
    query_id = request.args.get('id')
    items_list = StatisticItems.query.filter(
        StatisticItems.query_id == query_id, StatisticItems.final_price.isnot(None)).order_by(
            StatisticItems.end_time.asc()).all()
    return render_template(
        'favorite_searches/visualize_statistics.html',
        items_list=items_list,
        query_id=query_id)


@blueprint.route('/visualize_diagram')
def visualize_diagram():
    query_id = request.args.get('id')
    diagram = plot_statistics(query_id)
    output = io.BytesIO()
    diagram = FigureCanvas(diagram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')


@blueprint.route('/visualize_histogram')
def visualize_histogram():
    query_id = request.args.get('id')
    histogram = plot_histogram(query_id)
    output = io.BytesIO()
    histogram = FigureCanvas(histogram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')

webapp/templates/ebay_search/add_to_watch_list.html
{% extends "base.html" %} {% block content %}Товар успешно добавлен в
Избранное{% endblock %}

webapp/templates/ebay_search/pagination.html
<div class="row">
  <nav aria-label="Search results pages">
    <ul class="pagination">
      {% if not pagenumber or pagenumber|int() == 1 %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true"
          >Предыдущая</a
        >
      </li>
      {% else %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for(
                    'search.search',
                    q=request.args.get('q', ''),
                    categoryid=request.args.get('categoryid', ''),
                    pagenumber=(pagenumber|int() - 1)) }}"
          >Предыдущая</a
        >
      </li>
      {% endif %} {% for page in range(1, totalpages + 1) %} {% if
      pagenumber|int() == page %}
      <li class="page-item active" aria-current="page">
        <a
          class="page-link"
          href="{{ url_for(
                            'search.search',
                            q=request.args.get('q', ''),
                            categoryid=request.args.get('categoryid', ''),
                            pagenumber=page,
                            filters=request.args.get('filters', ''),
                            )}}"
          >{{ page }} <span class="sr-only">(current)</span></a
        >
      </li>
      {% else %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for(
                            'search.search',
                            q=request.args.get('q', ''),
                            categoryid=request.args.get('categoryid', ''),
                            pagenumber=page,
                            filters=request.args.get('filters', ''),
                            )}}"
          >{{ page }}
        </a>
      </li>
      {% endif %} {% endfor %} {% if pagenumber|int() == totalpages %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true"
          >Следующая</a
        >
      </li>
      {% else %}
      <li class="page-item">
        <a
          class="page-link"
          href="{{ url_for(
                    'search.search',
                    q=request.args.get('q', ''),
                    categoryid=request.args.get('categoryid', ''),
                    pagenumber=(pagenumber|int() + 1),
                    filters_request=request.args.get('filters', ''),
                    ) }}"
          >Следующая</a
        >
      </li>
      {% endif %}
    </ul>
  </nav>
</div>

webapp/templates/ebay_search/remove_from_watch_list.html
{% extends "base.html" %} {% block content %}Товар успешно удален из
Избранного{% endblock %}

webapp/templates/ebay_search/search.html
{% extends "base.html" %} {% block content %}
<div class="row my-2">
  {% with messages = get_flashed_messages() %} {% if messages %}
  <div class="alert alert-warning" role="alert">
    {% for message in messages %} {{ message }} {% endfor %}
  </div>
  {% endif %} {% endwith %}
</div>
<div class="row my-2">
  <div class="col-2"></div>
  <div class="col-8">
    <form class="form-inline" method="GET">
      <div class="input-group input-group-lg">
        <input type="text" class="form-control" placeholder="Поиск" name="q" 
          value="{{ request.args.get('q', '') }}" required>
          <select class="custom-select" name="categoryid" required>
              <option value="" {% if not request.args.get(
                'categoryid', '') %} selected {% endif %}>
                  Выберите категорию</option>
              {% for category in categories %}
                  <option {% if request.args.get(
                    'categoryid', '')== category.category_id|string() %} selected {% endif %}
                    value="{{category.category_id}}">
                    {{ category.category_name }}</option>
              {% endfor %}
          </select>
          <button type="submit" class="btn btn-secondary btn-lg">Поиск</button>
      </div>
  </form>
  </div>
  <div class="col-2"></div>
</div>

{% if request.args.get('q') %}
<!-- блок отображения выбранных фильтров -->
{% if userfilterslist %}
<div class="row my-2">
  <div class="col-2"></div>
  <div class="col-6">
    <h5>Примененные фильтры</h5>
    <div class="btn-group">
      {% for filters in userfilterslist %}
      <div class="my-1">
        {% for value in filters.filter_values %}
        <a
          role="button"
          class="btn btn-primary mx-1 my-1"
          href="{{ url_for(
                          'search.search',
                          q=request.args.get('q', ''),
                          categoryid=subcategoryid,
                          filters=new_filters_request(request.args.get('filters', ''), value),
                          ) }}"
          >{{ value }}</a
        >
        {% endfor%}
      </div>
      {% endfor%}
    </div>
  </div>
  <div class="col-4 mt-4">
    <form
      action="{{ url_for('favorite_searches.add_to_favorite_searches') }}"
      class="form-inline"
      method="GET"
      target="_blank"
    >
      <input type="hidden" name="q" value="{{ request.args.get('q', '') }}" />
      <input type="hidden" name="categoryid" value="{{ subcategoryid }}" />
      <input
        type="hidden"
        name="filters"
        value="{{ request.args.get('filters', '') }}"
      />
      <div class="input-group">
        <input
          type="text"
          class="form-control"
          placeholder="Имя запроса"
          name="query_name"
          value="{{ request.args.get('query_name', '') }}"
        />
      </div>
      <button type="submit" class="btn btn-primary mt-2">
        Сохранить параметры поиска
      </button>
    </form>
  </div>
</div>
{% endif%}
<!-- конец блока отображения выбранных фильтров -->

<div class="row">
  <!-- меню фильтров -->
  <div class="col-3">
    <h5>Фильтры</h5>
    <h5 name="subcategoryid" value="subcategory_id">
      Подкатегория: {{ subcategory }}
    </h5>
    <div class="dropdown">
      {% for aspect in histogram_container_data %}
      <div class="my-1">
        <button
          type="button"
          class="btn btn-info dropdown-toggle btn-block"
          data-toggle="dropdown"
          value="{{ aspect.aspect_name }}"
        >
          {{ aspect.aspect_name }}
        </button>
        <div class="dropdown-menu">
          {% for values in aspect.aspect_data %}
          <li class="form-check">
            <label class="form-check-label px-2">
              <input
                type="checkbox"
                class="form-check-input"
                value="{{ values.value_name }}"
              />{{ values.value_name }}: {{ values.count }}
            </label>
          </li>
          {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>
    <a
      class="btn btn-success btn-block my-1"
      role="button"
      href="{{ url_for(
                'search.search',
                q=request.args.get('q', ''),
                categoryid=subcategoryid,
                filters=request.args.get('filters', ''),
                ) }}"
      >Применить фильтры
    </a>
  </div>
  <!-- конец меню фильтров -->
  <div class="col-9">
    <h2>{{ title }}</h2>
    {% for item in results %}
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-sm-2">
          <div class="text-center">
            <img
              src="{{ item.gallery_url }}"
              class="img-thumbnail"
              alt="{{ item.title }}"
            />
          </div>
        </div>
        <div class="col-sm-10">
          <div class="card-body">
            <h5 class="card-title">
              <a href="{{ item.view_item_url }}" target="_blank"
                >{{ item.title }}</a
              >
            </h5>
            <p class="card-text">
              Текущая стоимость: {{ item.item_current_price }} USD
            </p>
            <div class="card-text">
              Состояние: {{ item.condition_display_name }}
            </div>
            <div class="card-text mt-1">
              Количество ставок: {{ item.bid_count }}
            </div>
            <p class="card-text">
              <small class="text-muted"
                >До конца аукциона: {{ item.time_left }}</small
              >
            </p>
            {% for wish in watch_list if wish.item_id == item.item_id %}
            <a
              href="{{ url_for('search.remove_from', itemid=item.item_id) }}"
              target="_blank"
              class="btn btn-outline-danger"
              role="button"
              >удалить из "Избранного"</a
            >
            {% else %}
            <a
              href="{{ url_for('search.add_to', itemid=item.item_id) }}"
              target="_blank"
              class="btn btn-outline-warning"
              role="button"
              >добавить в "Избранное"</a
            >
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% include 'ebay_search/pagination.html' %}
</div>
{% endif %} {% endblock %} {% block script %}
<script>
  $(document).ready(function () {
    const generateUrlParams = function (url) {
      let params = "";
      // url = decodeURIComponent(url)
      const buttons = $("button.dropdown-toggle");
      buttons.each(function (index) {
        const buttonText = $(this).text();
        const dropdown = $(this).next();
        const checkboxes = dropdown.find("input[type=checkbox]:checked");
        const checkboxesLength = checkboxes.length;
        if (checkboxesLength) {
          params += buttonText.trim() + ":";
        }
        checkboxes.each(function (index) {
          params += $(this).val();
          const checkboxNumber = index + 1;
          if (!(checkboxNumber === checkboxesLength)) {
            params += ",";
          }
        });
        const buttonNumber = index + 1;
        if (checkboxesLength) {
          params += ";";
        }
      });
      params = encodeURIComponent(params);
      return url + params;
    };
    const filterButton = $(".btn-success");
    const url = filterButton.attr("href");

    filterButton.on("click", function (e) {
      e.preventDefault();
      window.location = generateUrlParams(url);
    });
  });
</script>
{% endblock %}

webapp/templates/ebay_search/watch_list.html
{% extends "base.html" %} {% block content %}
<div class="row">
  <div class="col-12">
    <h2>{{ title }}</h2>
    {% for item in watch_list %}
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-sm-2">
          <div class="text-center">
            <img
              src="{{ item.gallery_url }}"
              class="img-thumbnail"
              alt="{{ item.title }}"
            />
          </div>
        </div>
        <div class="col-sm-10">
          <div class="card-body">
            <h5 class="card-title">
              <a href="{{ item.view_item_url }}">{{ item.title }}</a>
            </h5>
            <p class="card-text">
              {% if item.item_current_price_converted != '' %} Текущая
              стоимость: {{ item.item_current_price_converted }} USD {% else %}
              Текущая стоимость: {{ item.item_current_price }} USD {% endif %}
            </p>
            <div class="card-text mt-1">
              Количество ставок: {{ item.bid_count }}
            </div>
            <p class="card-text">
              {% if item.time_left == '0:00:00' %}
              <small class="text-muted">Время аукциона истекло</small>
              {% else %}
              <small class="text-muted"
                >До конца аукциона: {{ item.time_left }}</small
              >
              {% endif %}
            </p>
            <a
              href="{{ url_for('search.remove_from', itemid=item.item_id) }}"
              target="_blank"
              class="btn btn-outline-danger"
              role="button"
              >удалить из "Избранного"</a
            >
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

<!-- <a href="{{ url_for('.search', itemid=item.item_id, q=request.args.get('q', ''), categoryid=request.args.get('categoryid', '')) }}" target="_blank">добавить в избранное</a> -->