webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required
from webapp.ebay_search.get_category import get_ebay_categories

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    get_ebay_categories()
    title = "Панель управления"
    return render_template('admin/index.html', page_title=title)

webapp/ebay_search/views.py
from flask import Blueprint, flash, render_template, request

from webapp.ebay_search.find_items import (
    find_items_advanced, add_to_watch_list, get_user_watch_list,
    remove_from_user_watch_list, get_user_filters_request,
)
from webapp.ebay_search.models import EbayCategories
from webapp.user.decorators import user_required


blueprint = Blueprint('search', __name__, url_prefix='/search')


@blueprint.route('/')
@user_required
def search():
    # получаем категории товаров Ebay из базы данных для отображения на поисковой странице
    categories = EbayCategories.query.filter_by(
        category_level=1)
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем номер выбранной страницы, по умолчанию номер страницы = 1
    page_number = request.args.get('pagenumber')
    if not page_number:
        page_number = 1
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем значение фильтра, удаляемое из поискового запроса
    if filters_request:
        user_filters_list = get_user_filters_request(filters_request)
    else:
        user_filters_list = None
    # При направлении любого поискового запроса получаем с Ebay список 
    # избранных лотов пользователя
    if q:
        watch_items = get_user_watch_list()


    # обрабатываем поисковый запрос пользователя, номер выбранной страницы,
    # фильтры и передаем его в html
    if q:
        (results, total_pages, subcategory, subcategory_id, histogram_container_data
            ) = find_items_advanced(
            q,
            chosen_categoryid,
            page_number=page_number,
            user_filters_list=user_filters_list)

    search_request = {
        'title': 'Результаты поиска' if q else None,
        'categories': categories,
        'pagenumber': page_number,
        'userfilterslist': user_filters_list,
        'watch_list': watch_items if q else None,
        'results': results if q else None,
        'totalpages': total_pages if q else None,
        'subcategory': subcategory if q else None,
        'subcategoryid': subcategory_id if q else None,
        'histogram_container_data': histogram_container_data if q else None,
    }

    return render_template(
        'ebay_search/search.html',
        **search_request)


@blueprint.route('/add_to_watch_list')
def add_to():
    item_id = request.args.get('itemid')
    if item_id:
        add_to_watch_list(item_id)

        return render_template('ebay_search/add_to_watch_list.html')


@blueprint.route('/watch_list')
@user_required
def open_watch_list():
    watch_items = get_user_watch_list()
    return render_template(
        'ebay_search/watch_list.html', watch_list=watch_items)


@blueprint.route('/remove_item')
def remove_from():
    item_id = request.args.get('itemid')
    if item_id:
        remove_from_user_watch_list(item_id)
        return render_template('ebay_search/remove_from_watch_list.html')


@blueprint.context_processor
def filter_processor():
    def delete_filter_from_request(filters_request, value):
        """
        Функция удаляет фильтр из списка избранных фильтров
        пользователя по запросу с html
        """
        user_filters_request = get_user_filters_request(filters_request)
        for filters in user_filters_request:
            if (len(filters['filter_values']) == 1 and
                    value in filters['filter_values']):
                user_filters_request.remove(filters)
            elif value in filters['filter_values']:
                filters['filter_values'].remove(value)
        new_filters_request = ''
        for filters in user_filters_request:
            new_filters_request += f"{filters['filter_name']}:"
            for value in filters['filter_values']:
                new_filters_request += f"{value};"
        return new_filters_request
    return dict(new_filters_request=delete_filter_from_request)

webapp/favorite_searches/views.py
import io
from datetime import datetime
from flask import Blueprint, request, render_template, Response
from flask_login import current_user
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

from webapp import db
from webapp.favorite_searches.diagram_mpl import plot_statistics, plot_histogram
from webapp.favorite_searches.models import FavoriteSearches, StatisticItems
from webapp.user.decorators import user_required


blueprint = Blueprint(
    'favorite_searches', __name__, url_prefix='/favorite_searches')


@blueprint.route('/')
@user_required
def open_favorite_searches():
    favorite_searches_list = FavoriteSearches.query.filter(
        FavoriteSearches.user_id == current_user.id).order_by(
            FavoriteSearches.date_of_creation.desc()).all()

    return render_template(
        'favorite_searches/favorite_searches.html',
        favorite_searches_list=favorite_searches_list
    )


@blueprint.route('/add_to_favorite_searches')
@user_required
def add_to_favorite_searches():
    """
    Функция добавляет поиск в базу данных "Избранные поиски"
    """
    # получаем результаты запроса от пользователя из поисковой строки
    q = request.args.get('q')
    # получаем выбранную категорию со страницы поиска
    chosen_categoryid = request.args.get('categoryid')
    # получаем значения выбранных фильтров расширенного поиска
    filters_request = request.args.get('filters')
    # получаем имя сохраненного поискового запроса
    query_name = request.args.get('query_name')

    user_query_exists = FavoriteSearches.query.filter(
        FavoriteSearches.user_query == q).count()
    if not user_query_exists:
        new_user_query = FavoriteSearches(
            user_id=current_user.id,
            query_name=query_name,
            user_query=q,
            chosen_categoryid=chosen_categoryid,
            filter_request=filters_request,
        )
        db.session.add(new_user_query)
        db.session.commit()

        return render_template(
            'favorite_searches/add_to_favorite_searches.html')


@blueprint.route('/remove_from_favorite_searches')
def remove_from_favorite_searches():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        db.session.delete(favorite_search)
        db.session.commit()
        title = "Поиск успешно удален из 'Избранных поисков'"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/add_statistic')
def add_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = True
        favorite_search.statistic_start_date = datetime.now()
        db.session.commit()
        title = "Сбор статистики цен включен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/stop_statistic')
def stop_statistic():
    search_id = request.args.get('id')
    if search_id:
        favorite_search = FavoriteSearches.query.filter(
            FavoriteSearches.id == search_id).first()
        favorite_search.statistic_status = False
        favorite_search.statistic_start_date = None
        db.session.commit()
        title = "Сбор статистики цен выключен"
        return render_template(
            'favorite_searches/favorite_searches_action.html', title=title)


@blueprint.route('/visualize_statistics')
def visualize_statistics():
    query_id = request.args.get('id')
    items_list = StatisticItems.query.filter(
        StatisticItems.query_id == query_id, StatisticItems.final_price.isnot(None)).order_by(
            StatisticItems.end_time.asc()).all()
    return render_template(
        'favorite_searches/visualize_statistics.html',
        items_list=items_list,
        query_id=query_id)


@blueprint.route('/visualize_diagram')
def visualize_diagram():
    query_id = request.args.get('id')
    diagram = plot_statistics(query_id)
    output = io.BytesIO()
    diagram = FigureCanvas(diagram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')


@blueprint.route('/visualize_histogram')
def visualize_histogram():
    query_id = request.args.get('id')
    histogram = plot_histogram(query_id)
    output = io.BytesIO()
    histogram = FigureCanvas(histogram).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')

webapp/user/views.py
from datetime import datetime
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp import db
from webapp.user.decorators import user_required
from webapp.user.get_user_token import get_token_url, get_token
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User


blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/')
def login():
    if (current_user.is_authenticated and
            current_user.token is None):
        return redirect(url_for('user.redirect_user'))
    elif (current_user.is_authenticated and
            current_user.hard_expiration_time < datetime.now()):
        return redirect(url_for('user.redirect_user'))
    elif current_user.is_authenticated and current_user.token:
        return redirect(url_for('search.search'))
    else:
        title = "Авторизация"
        login_form = LoginForm()
        return render_template(
            'user/login.html',
            page_title=title,
            form=login_form
            )


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно вошли на сайт')
            return redirect(url_for('user.login'))

    flash('Неправильное имя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('user.login'))


@blueprint.route('/get_token')
@user_required
def redirect_user():
    title = "Привязать аккаунт eBay"
    token_url = get_token_url()
    return render_template(
        'get_token/get_token.html',
        page_title=title,
        get_token_url=token_url
        )


@blueprint.route('/token')
def recieve_user_token():
    # после подтверждения пользователем допуска к своим данным Ebay,
    # он перенаправляется на домашнюю страницу,
    # где запускается функция получения токена
    user_token_status_invalid = current_user.session_id_status and\
        not current_user.token or current_user.hard_expiration_time < datetime.now()
    if current_user.is_authenticated and user_token_status_invalid:
        get_token()
        if current_user.token_status:
            title = "Вы успешно подключили ваш Ebay-аккаунт"
        else:
            title = "Процесс подключения аккаунта Ebay не был завершен"
        print(title)
        return render_template(
            'get_token/get_token_success.html',
            title=title,
            )
    elif current_user.is_authenticated and current_user.token:
        return redirect(url_for('search.search'))
    else:
        return render_template('index_page/main_index.html')


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect('get_token.html')
    form = RegistrationForm()
    title = "Регистрация"
    return render_template(
        'user/registration.html',
        page_title=title,
        form=form,
        )


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            role='user',
            )
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегистрировались!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error)
                )
        return redirect(url_for('user.register'))

webapp/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>{{ page_title }}</title>
  </head>
  <body>
    {% if current_user.is_authenticated and current_user.token_status %} {%
    include 'menu.html' %} {% endif %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    {% block script %}{% endblock %}
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('search.search') }}"
    >Поиск по EBay</a
  >
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('search.open_watch_list') }}"
          >Избранное</a
        >
      </li>
      <li class="nav-item active">
        <a
          class="nav-link"
          href="{{ url_for('favorite_searches.open_favorite_searches') }}"
          >Избранные поиски</a
        >
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <span class="nav-link">Привет, {{ current_user.username }}!</span>
      </li>
      {% if current_user.is_admin %}
      <li class="nav-item">
        <a href="{{ url_for('admin.admin_index') }}" class="nav-link"
          >Админка</a
        >
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.register') }}"
          >Регистрация</a
        >
      </li>
      {% endif %}
    </ul>
  </div>
</nav>